name: Check Neovim release

on:
  schedule:
    - cron: "0 0,12 * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    outputs:
      version: ${{ steps.version.outputs.version }}
      released: ${{ steps.check.outputs.released }}
    steps:
      - name: Get latest Neovim release
        id: version
        run: |
          version="$(
            gh release view \
              --repo neovim/neovim \
              --json tagName \
              --jq '.tagName'
          )"

          echo "version=$version" >> "$GITHUB_OUTPUT"
      - name: Check release
        id: check
        run: |
          version="${{ steps.version.outputs.version }}"
          
          if gh release view "$version" >/dev/null 2>&1; then
            echo "released=true" >> "$GITHUB_OUTPUT"
          else
            echo "released=false" >> "$GITHUB_OUTPUT"
          fi
  build:
    needs: check
    if: needs.check.outputs.released == 'false'
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ needs.check.outputs.version }}
